# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b177d34bf887d6488e7ab3f4ceee446bfda1ded21b70624218572fef25c467ce2c081a3a1940531be6a6e833d8d977f4215fc6585f8116af8d79bd160a53cee5

test:
  secret_key_base: 6e34debedfb7957331ed9786bd8b4983c9a5c2e22bb638bbb9d05474d681d9e3687a86cc43fef0b75b9433bd984bddd0bbcda04b386276a52afd66d3e56f326b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
